name: 'Setup project'
description: 'Install dependencies and other project setup'
runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: pip install poetry==${{ env.POETRY_VERSION }}
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      id: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'poetry'
    - name: Install dependencies
      shell: bash
      run: |
        poetry env use '${{ steps.cp310.outputs.python-path }}'
        poetry install --remove-untracked
